#!/bin/sh
set -e

json=node_modules/.bin/json
if ! [ -x "$json" ]; then
  npm install --silent
fi

tmp="$(mktemp)"
remove_tmp () {
  rm -f "$tmp"
}
trap remove_tmp EXIT
curl -s "https://blueoakcouncil.org/copyleft.json" > "$tmp"

version=$($json version < "$tmp")
semver="$version.0.0"
echo "Version $semver"
npm version "$semver"
git push --follow-tags
npm publish
